/**
 * FLOWZORA YouTube Audio Extraction Worker
 * Runs on Railway with yt-dlp + ffmpeg installed in the container.
 *
 * Why this works when Vercel doesn't:
 * - Railway IPs are not in YouTube's cloud-datacenter blocklist
 * - yt-dlp is actively maintained to keep pace with YouTube anti-bot updates
 * - A real JS runtime (node 22) + yt-dlp-ejs solves YouTube's n-signature
 *   challenge, which yt-dlp has required an external runtime for since 2025.11.12
 * - Authenticated requests via YOUTUBE_COOKIE env var bypass age-gates
 */

const express = require('express');
const { execFile, spawn } = require('child_process');
const { promisify } = require('util');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');

const execFileAsync = promisify(execFile);
const app = express();
app.use(express.json({ limit: '1mb' }));

const PORT = process.env.PORT || 3001;
// Prefer the token scoped to this worker; fall back to the shared one so an
// existing deployment keeps authenticating after an upgrade. The Vercel side
// (src/lib/pipeline/youtube.ts) resolves its token in the same order.
// .trim() is load-bearing: dashboard UIs (Render's value field is a textarea)
// routinely store a trailing newline with a pasted secret, and an untrimmed
// compare then fails with a 401 that looks exactly like a wrong token.
const WORKER_SECRET_TOKEN = (
  process.env.YOUTUBE_WORKER_TOKEN || process.env.WORKER_SECRET_TOKEN || ''
).trim();

// Max audio size: 20MB cap — covers ~30 minutes of podcast audio
const MAX_AUDIO_BYTES = 20 * 1024 * 1024;

// Must stay BELOW the caller's AbortSignal.timeout(45_000) in youtube.ts, so a
// slow extraction returns a real error we can log instead of being severed
// mid-stream by the client with no diagnosis.
const EXTRACT_TIMEOUT_MS = Number(process.env.EXTRACT_TIMEOUT_MS) || 40_000;

// ── Health check ──────────────────────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'flowzora-yt-worker', ts: new Date().toISOString() });
});

// ── Auth middleware ───────────────────────────────────────────────────────────
function requireAuth(req, res, next) {
  if (!WORKER_SECRET_TOKEN) return next(); // open if no secret set (dev mode)
  const auth = (req.headers['authorization'] || '').trim();
  if (auth === `Bearer ${WORKER_SECRET_TOKEN}`) return next();
  res.status(401).json({ error: 'Unauthorized' });
}

// ── Write cookies to a temp Netscape file ────────────────────────────────────
function writeCookieFile(cookieString) {
  if (!cookieString || !cookieString.trim()) return null;
  const tmpPath = path.join(os.tmpdir(), `yt_cookies_${crypto.randomBytes(6).toString('hex')}.txt`);

  // If it's already Netscape format, write as-is
  if (cookieString.includes('\t') || cookieString.includes('# Netscape') || cookieString.includes('#HttpOnly_')) {
    fs.writeFileSync(tmpPath, cookieString, 'utf8');
    return tmpPath;
  }

  // If it's a JSON array [{name, value}] format, convert to Netscape
  if (cookieString.trim().startsWith('[')) {
    try {
      const arr = JSON.parse(cookieString);
      const lines = ['# Netscape HTTP Cookie File', '# Generated by FLOWZORA worker'];
      for (const c of arr) {
        if (c.name && c.value != null) {
          lines.push([
            c.domain || '.youtube.com',
            'TRUE',
            c.path || '/',
            c.secure ? 'TRUE' : 'FALSE',
            c.expirationDate ? Math.floor(c.expirationDate) : 0,
            c.name,
            c.value,
          ].join('\t'));
        }
      }
      fs.writeFileSync(tmpPath, lines.join('\n'), 'utf8');
      return tmpPath;
    } catch (_) {}
  }

  // Semicolon-separated key=value: convert to Netscape
  if (cookieString.includes('=') && !cookieString.includes('\n')) {
    const pairs = cookieString.split(/;\s*/);
    const lines = ['# Netscape HTTP Cookie File', '# Generated by FLOWZORA worker'];
    for (const pair of pairs) {
      const eqIdx = pair.indexOf('=');
      if (eqIdx < 1) continue;
      const name = pair.slice(0, eqIdx).trim();
      const value = pair.slice(eqIdx + 1).trim();
      if (name) {
        lines.push(['.youtube.com', 'TRUE', '/', 'FALSE', 0, name, value].join('\t'));
      }
    }
    fs.writeFileSync(tmpPath, lines.join('\n'), 'utf8');
    return tmpPath;
  }

  // Fallback: write raw (let yt-dlp try to parse it)
  fs.writeFileSync(tmpPath, cookieString, 'utf8');
  return tmpPath;
}

// ── Core extraction: yt-dlp → stdout ─────────────────────────────────────────
async function extractAudioBuffer(videoUrl, cookieString) {
  const cookiePath = writeCookieFile(
    cookieString || process.env.YOUTUBE_COOKIE || process.env.YOUTUBE_COOKIES || ''
  );

  const args = [
    '--no-playlist',
    '--quiet',
    '--no-warnings',
    // Output format: best audio stream, prefer m4a/opus, max 128k
    '-f', 'bestaudio[filesize<20M]/bestaudio',
    // Extract audio only, re-encode to 64kbps mp3 via ffmpeg — lightweight for Whisper
    '-x',
    '--audio-format', 'mp3',
    '--audio-quality', '64K',
    // Solve YouTube's n-signature challenge. Only `deno` is enabled by default,
    // so node must be opted into explicitly; it also needs yt-dlp-ejs, which the
    // Dockerfile pulls in via the yt-dlp[default] extra.
    '--js-runtimes', 'node',
    // Cap download size
    '--max-filesize', '20M',
    // Output to stdout as raw bytes
    '-o', '-',
  ];

  if (cookiePath) {
    args.push('--cookies', cookiePath);
  }

  // Add video URL last
  args.push(videoUrl);

  console.log(`[Worker] Extracting audio from: ${videoUrl}`);
  console.log(`[Worker] yt-dlp args: ${args.filter(a => !a.includes('cookie')).join(' ')}`);

  return new Promise((resolve, reject) => {
    const proc = spawn('yt-dlp', args, { stdio: ['ignore', 'pipe', 'pipe'] });

    const chunks = [];
    let totalBytes = 0;
    let stderr = '';
    let killed = false;

    // Global timeout, declared before the handlers that clear it so there is no
    // temporal-dead-zone hazard. Cleared on close/error so it cannot outlive the
    // request or SIGTERM a recycled pid.
    const timer = setTimeout(() => {
      proc.kill('SIGTERM');
      reject(new Error(`yt-dlp timed out after ${Math.round(EXTRACT_TIMEOUT_MS / 1000)} seconds`));
    }, EXTRACT_TIMEOUT_MS);

    proc.stdout.on('data', (chunk) => {
      chunks.push(chunk);
      totalBytes += chunk.length;
      // Hard cap: stop reading once we hit MAX_AUDIO_BYTES
      if (totalBytes >= MAX_AUDIO_BYTES && !killed) {
        killed = true;
        proc.kill('SIGTERM');
      }
    });

    proc.stderr.on('data', (d) => {
      stderr += d.toString();
    });

    proc.on('close', (code) => {
      clearTimeout(timer);
      // Clean up cookie file
      if (cookiePath) {
        try { fs.unlinkSync(cookiePath); } catch (_) {}
      }

      const buf = Buffer.concat(chunks);

      if (buf.length > 1024) {
        // Success — even if we killed the process due to size cap
        console.log(`[Worker] Extracted ${(buf.length / (1024 * 1024)).toFixed(2)} MB audio`);
        resolve(buf);
      } else if (code === 0 || killed) {
        reject(new Error('yt-dlp produced no output (empty audio stream)'));
      } else {
        const errMsg = stderr.slice(-500) || `yt-dlp exited with code ${code}`;
        console.error(`[Worker] yt-dlp error (code ${code}): ${errMsg}`);
        reject(new Error(errMsg));
      }
    });

    proc.on('error', (err) => {
      clearTimeout(timer);
      if (cookiePath) {
        try { fs.unlinkSync(cookiePath); } catch (_) {}
      }
      reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
    });
  });
}

// ── GET /debug-cookie ─────────────────────────────────────────────────────────
// Reports how the configured cookie blob PARSES, never what it contains.
// Cookie names are structural (SID, HSID...) and are what diagnose an auth
// failure; values are secrets and are never read, logged, or returned.
app.get('/debug-cookie', requireAuth, (req, res) => {
  const raw = process.env.YOUTUBE_COOKIE || process.env.YOUTUBE_COOKIES || '';
  if (!raw) return res.json({ configured: false });

  const detected =
    raw.trim().startsWith('[') ? 'json'
    : (raw.includes('\t') || raw.includes('# Netscape') || raw.includes('#HttpOnly_')) ? 'netscape'
    : (raw.includes('=') && !raw.includes('\n')) ? 'semicolon'
    : 'unknown';

  let names = [];
  let parseError = null;
  try {
    const cp = writeCookieFile(raw);
    const written = fs.readFileSync(cp, 'utf8');
    // A valid Netscape row is 7 TAB-separated fields; the name is field 6.
    names = written
      .split('\n')
      .filter((l) => l && !l.startsWith('#'))
      .map((l) => l.split('\t'))
      .filter((f) => f.length >= 7)
      .map((f) => f[5]);
    fs.unlinkSync(cp);
  } catch (e) {
    parseError = e.message;
  }

  // Cookies YouTube needs for a genuinely authenticated session.
  const required = ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', '__Secure-1PSID'];
  res.json({
    configured: true,
    rawLength: raw.length,
    detectedFormat: detected,
    containsTabs: raw.includes('\t'),
    containsNewlines: raw.includes('\n'),
    cookiesParsed: names.length,
    cookieNames: names,
    missingAuthCookies: required.filter((r) => !names.includes(r)),
    parseError,
  });
});

// ── POST /extract-audio ───────────────────────────────────────────────────────
app.post('/extract-audio', requireAuth, async (req, res) => {
  const { url, videoId, cookie } = req.body;

  if (!url && !videoId) {
    return res.status(400).json({ error: 'url or videoId is required' });
  }

  const videoUrl = url || `https://www.youtube.com/watch?v=${videoId}`;

  try {
    const audioBuffer = await extractAudioBuffer(videoUrl, cookie);

    // Return raw MP3 bytes — Vercel reads arrayBuffer() from response
    res.set('Content-Type', 'audio/mpeg');
    res.set('Content-Length', audioBuffer.length.toString());
    res.set('X-Audio-Size-Bytes', audioBuffer.length.toString());
    res.send(audioBuffer);
  } catch (err) {
    console.error(`[Worker] Extraction failed for ${videoUrl}:`, err.message);
    res.status(500).json({ error: err.message || 'Audio extraction failed' });
  }
});

// ── GET /extract-audio (for quick curl tests) ─────────────────────────────────
app.get('/extract-audio', requireAuth, (req, res) => {
  res.json({ status: 'ready', method: 'POST', body: '{ url, videoId, cookie }' });
});

app.listen(PORT, () => {
  console.log(`[Worker] FLOWZORA YouTube extraction worker running on :${PORT}`);
  console.log(`[Worker] Auth: ${WORKER_SECRET_TOKEN ? 'enabled' : 'disabled (set WORKER_SECRET_TOKEN)'}`);
  console.log(`[Worker] Cookie: ${(process.env.YOUTUBE_COOKIE || process.env.YOUTUBE_COOKIES) ? 'configured' : 'not set'}`);

  // Verify yt-dlp is installed
  execFileAsync('yt-dlp', ['--version'])
    .then(({ stdout }) => console.log(`[Worker] yt-dlp version: ${stdout.trim()}`))
    .catch(() => console.error('[Worker] WARNING: yt-dlp not found! Install with: pip3 install yt-dlp'));
});
